<section id="content" class="clearfix">
	<div class="main col1-layout clearfix">
		<div class="wrapper">
			<div class="col-main clearfix">
				<div class="account-login">
					<div class="page-title">
						<h1>Cancel card</h1>
					</div>
					 <div class="pageWrapper clearfix">
					<?php if ($this->cancel === false) { ?>
					    <ul class="form-list">
						<li>
						     <?php if (!empty ($this->errorMessages['card'])) { ?>
						     <h2><?php echo $this->errorMessages['card'] ; ?></h2>
						     <?php } else {?>
						     <h2>Your card has been canceled</h2>
						     <?php }?>
						     <a href="/account">Return to Account</a>
						</li>
						</ul>
					<?php } /* else if ( empty($this->cardDetails) ) { ?>
					    <ul class="form-list">
						<li>
						    <h2>In valid Request</h2>
						</li>
						</ul>
					<?php } */ else { ?>
					<form method="post" action="<?php echo '/card/cancel/clr/1/cid/' . $this->cardDetails->id?>" name="reset_password" id="reset_password">
						<h2>Are you sure you want to delete this card?</h2>
						<ul class="form-list">
						<li>
                            <h3><?php echo $this->cardDetails->cardnumber ?> (<?php echo $this->cardDetails->cardname?>)</h3>
                            </br>
                            <div class="field clearfix">
								<label for="password" class="required"><em>*</em>Your login password</label>
								<div class="input-box">
									<input type="password" name="password"  autocomplete="off" class="input-text required-entry validate-password <?php if ($this->error) echo 'validation-failed'; ?>"/>
									<div class="validation-advice" style="">
										<?php if (isset($this->errorMessages['password'])) echo $this->errorMessages['password']; ?>
									</div>
								</div>
							</div>
                            </br>
                            Note: Any existing scheduled payments associated with this card will NOT be deleted.
                            To stop a Scheduled payment please contact us on 0844 800 9507.
						</li>
						</ul>
						<input type="submit"  name="cancel_card" value="Cancel Card" class="button login-btn floatright" />
						<a class="" href="/account"><i class="icon-left-open"></i> Back</a>
						
						
					</form>
					<?php } ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>