<footer class="clearfix">
	<div class="wrapper">
		<div class="cookieMessage clearfix">
		<span class="top">^</span>
			<p>Our site uses cookies. <a href="#" >Find out what cookies are and why we use them</a>. If you continue to use our site you consent to us using cookies in this way.</p>
		</div>
		<nav role="navigation" id="footerMenu" class="clearfix">
			<ul class="level1">
				<li class="first"><a href="#" title="About ASDA Cards">About ASDA Cards</a>
					<ul class="level2">
						<li class="first"><a href="#" title="Buying a Card">Buying a Card</a></li>
						<li class=""><a href="#" title="Using a Card">Using a Card</a></li>
						<li class=""><a href="#" title="Topping up">Topping up</a></li>
						<li class="last"><a href="#" title="Delivery Information">Delivery Information</a></li>
					</ul>
				</li>
				<li><a href="#"  title="Customer Services">Customer Services</a>
					<ul class="level2">
						<li>0844 800 9244 | <a href="mailto:customerservices@asdacards.co.uk">customerservices@asdacards.co.uk</a> | 123 Fake Street, Blahville, Blahtown, FA2 4KE</li>
					</ul>
				</li>
				<li class="last"><a href="#" title="ASDA Websites">ASDA Websites</a>
					<ul class="level2">
						<li class="first"><a href="http://asda.com" title="Asda.com">Asda.com</a></li>
						<li class=""><a href="http://direct.asda.com" title="Asda.com">ASDA Direct</a></li>
						<li class=""><a href="http://george.asda.com" title="George">George</a></li>
						<li class=""><a href="http://groceries.asda.com" title="ASDA Groceries">ASDA Groceries</a></li>
						<li class="last"><a href="http://money.asda.com" title="ASDA Money">ASDA Money</a></li>
					</ul>
				</li>
			</ul>
		</nav>
		<div class="footerBottom clearfix">
			<ul>
				<li class="first"><h3>&copy; ASDA 2013</h3></li>
				<li><a href="#" >Terms &amp; Conditions</a></li>
				<li><a href="#" title="Terms of use">Terms of use</a></li>
				<li><a href="#" >Cookie Policy</a></li>
				<li><a href="#" title="Privacy Policy">Privacy Policy</a></li>
				<li class="last"><a href="#" title="Sitemap">Sitemap</a></li>
				<li class="footerLogo"><img src="/img/footer-logo.png" alt="ASDA - Saving you money every day" />
			</ul>
		</div>
	</div>
</footer>