<section id="content" class="clearfix">
	<div class="main clearfix">
		<div class="wrapper">
			<div class="flexslider clearfix">
				<ul class="slides">
					<li>
						<div class="caption">
							<h1>ASDA Cards</h1>
							<h2>A new year, a new way to save</h2>
						</div>
						<img src="img/slides/slide1.png" alt="Slide1" />
					</li>
					<li>
						<div class="caption">
							<h2>Christmas Savings Card</h2>
							<h3>A new year, a new way to save</h3>
						</div>
						<img src="img/slides/slide2.png" alt="Slide2" />
					</li>
				</ul>
			</div>
			<div class="pageWrapper">
				<div class="column-25-25-25-25 clearfix">
					<div class="col1 nav-widget">
						<img src="http://magento.jml-staging.com/media/asda/card.png" alt="Card Pic" />
						<i class="icon-right-open floatright"></i>
						<h2>Gift Cards<br />&#160;</h2>
						<div class="caption">
							<a href="#">
								<i class="icon-right-open floatright"></i>
								<h2>Gift Cards</h2>
								<h3>The Perfect gift for everyone</h3>
							</a>
						</div>
					</div>
					<div class="col2 nav-widget">
						<img src="http://magento.jml-staging.com/media/asda/card.png" alt="Card Pic" />
						<i class="icon-right-open floatright"></i>
						<h2>eGifts<br />&#160;</h2>
						<div class="caption">
							<a href="#">
								<i class="icon-right-open floatright"></i>
								<h2>eGifts</h2>
								<h3>The Perfect gift for everyone</h3>
							</a>
						</div>
					</div>
					<div class="col3 nav-widget">
						<img src="http://magento.jml-staging.com/media/asda/card.png" alt="Card Pic" />
						<i class="icon-right-open floatright"></i>
						<h2>Christmas Savings Card</h2>
						<div class="caption">
							<a href="#">
								<i class="icon-right-open floatright"></i>
								<h2>Christmas Savings Card</h2>
								<h3>The Perfect gift for everyone</h3>
							</a>
						</div>
					</div>
					<div class="col4 nav-widget">
						<img src="http://magento.jml-staging.com/media/asda/card.png" alt="Card Pic" />
						<i class="icon-right-open floatright"></i>
						<h2>High street gift cards</h2>
						<div class="caption">
							<a href="#">
								<i class="icon-right-open floatright"></i>
								<h2>Gift Cards</h2>
								<h3>The Perfect gift for everyone</h3>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>