<section id="content" class="clearfix">
	<div class="main col1-layout clearfix">
		<div class="wrapper">
			<div class="col-main clearfix">
				<div class="account-login">
					<div class="page-title">
						<h1>Forgot Your Password?</h1>
					</div>
					 <div class="pageWrapper clearfix">
					<?php if ($this->linkSend) { ?>
					    <ul class="form-list">
						<li>
						    <h2>We’ve sent an email to <?php echo $this->email?> containing a temporary link that will allow you to reset your password for the next 24 hours. Please check your spam folder if the email doesn’t appear within a few minutes</h2>
						    <h2>Return to <a href="/login"> sign in</a><h2>
						</li>
						</ul>
					<?php } else { ?>
					<form method="post" action="/login/forgot-password" name="forgot_password" id="forgot_password">

						<h2>Please enter your email address below. You will receive a link to reset your password.</h2>
						<ul class="form-list">
						<li>
						<label class="required" for="email_address">
							<em>*</em>
							Email Address
						</label>
						<div class="input-box">
						<input id="email_address" class="input-text required-entry validate-email" type="text" value="" alt="email" name="email">
						    <div class="validation-advice" style="">
							    <?php if ($this->errorMessage) echo $this->errorMessage; ?>
						    </div>
						</div>
						</li>
						</ul>
						<input type="submit"  name="forgot_password" value="Submit" class="button login-btn floatright" />
						
					</form>
					<?php } ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>