<section id="content" class="clearfix">
	<div class="main col1-layout clearfix">
		<div class="wrapper">
			<div class="col-main clearfix">
				<div class="account-login">
					<div class="page-title">
						<h1>Reset Your Password</h1>
					</div>
					 <div class="pageWrapper clearfix">
					<?php if ($this->success) { ?>
					    <ul class="form-list">
						<li>
						    <h2>Your password has been reset.</h2>
						     <h2>Return to <a href="/login"> sign in</a><h2></h2>
						</li>
						</ul>
					<?php } else if (!empty($this->keyErrorMessage)) { ?>
					    <ul class="form-list">
						<li>
						    <h2><?php echo $this->keyErrorMessage ?></h2>
						    <!-- <h2>Return to <a href="/login"> sign in</a><h2> -->
						</li>
						</ul>
					<?php } else { ?>
					<form method="post" action="/login/reset-password/k/<?php echo $this->resetKey ?>" name="reset_password" id="reset_password">
						<h2>Please fill in the form below to reset your password.</h2>
						<ul class="form-list">
						<li>
							<div class="field clearfix">
								<label for="security_answer" class="required"><em>*</em>Security Question </label>
								<label for="security_answer" class="required"> <b><?php echo $this->securityQuestion ; ?></b></label>   
								<div class="input-box">
									<!-- <select type="text" name="security_question" value="<?php if (isset($_POST['security_answer'])  ) echo $_POST['security_answer'];?>" class="input-text validate-email required-entry">
									 <option value="Mothers maiden name">Mothers maiden name</option>
									 <option value="Favorite colour">Favorite colour</option>
									 <option value="Name of first pet">Name of first pet</option>
									</select> -->   
								</div>
							</div>
							<div class="field clearfix">
								<label for="security_answer" class="required"><em>*</em>Security Answer</label>
								<div class="input-box">
									<input type="text" name="security_answer" value="<?php if (isset($_POST['security_answer'])) echo $_POST['security_answer'];?>" class="input-text required-entry <?php if (!empty($this->errorMessage['securityanswer']) && isset($_POST['register'] )) echo 'validation-failed'; ?>" />   
									<div class="validation-advice" style="">
										<?php if (isset($this->errorMessage['securityanswer'])) echo $this->errorMessage['securityanswer']; ?>
									</div>
								</div>
							</div>
							<div class="field clearfix">
								<label for="password" class="required"><em>*</em>Password</label>
								<div class="input-box">
									<input type="password" name="user_password_new"  autocomplete="off" class="input-text required-entry validate-password <?php if (!empty($registration->errors['password']) && isset($_POST['register'] ) ) echo 'validation-failed'; ?>"/>
									<div class="validation-advice" style="">
										<?php if (isset($this->errorMessage['password'])) echo $this->errorMessage['password']; ?>
									</div>
								</div>
							</div>
							<div class="field clearfix">
								<label for="confirmation" class="required"><em>*</em>Confirm Password</label>
								<div class="input-box">
									<input type="password" name="user_password_repeat"  autocomplete="off"  class="input-text required-entry validate-cpassword <?php if (!empty($registration->errors['password_not_same']) && isset($_POST['register'] )) echo 'validation-failed'; ?>" />  
									<div class="validation-advice" style="">
										<?php if (isset($this->errorMessage['password_not_same'])) echo $this->errorMessage['password_not_same']; ?>
									</div>
								</div>
							</div>
						</li>
						</ul>
						<input type="submit"  name="reset_password" value="Submit" class="button login-btn floatright" />
						
					</form>
					<?php } ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>