<section id="content" class="clearfix">
	<div class="main col1-layout clearfix">
		<div class="wrapper">
				<div class="my-account">
					<div class="dashboard clearfix">
						<div class="page-title account-title">
							<h1>Account Management</h1>
						</div>
					<div class="pageWrapper clearfix">
					<?php if(!empty($this->message)) { ?>
					<div class="messages">
						<h2><?php echo $this->message ; ?></h2>
					</div>
					<?php
						} 
					?>
						<div class="welcome-msg">
							<h2 class="sub-title">Hello, <?php echo $this->userDetails->first_name .' '. $this->userDetails->last_name?></h2>
							<p>From your My Account Dashboard you have the ability to view a snapshot of your recent account activity and update your account information. Select a link below to view or edit information.</p>
						</div>
						<div class="my-cards widget">
							<h2 class="legend">My Cards <a href="/card/register" class="addcard button floatright">Add Card</a></h2>
							<?php if ($this->userCardDetails) {?>
							<table id="my-cards-table" class="data-table clearfix">
								<thead>
									<tr class="">
										<th>Card No.</th>
										<th>Card Name</th>
										<th>Balance</th>
										<th> </th>
										<th> </th>
										<th> </th>
									</tr>
								</thead>
								<tbody>
								<?php foreach ($this->userCardDetails as $card) {?>
									<tr class="">
										<td><?php echo $card->cardnumber?></td>
										<td><?php echo $card->cardname?></td>
										<td>
											<span class="price">&pound;<?php echo $card->balance?></span>
										</td>
										<td class="a-center actions">
											<a class="" href="<?php echo '/topup/index/cid/' . $card->cardId; ?>">Topup</a>
										</td>
										<td class="a-center actions">
											<a class="" href="<?php echo '/topup/schedule/cid/' . $card->cardId; ?>">Scheduled topup</a>
										</td>
										<td class="a-center actions">
											<a class="" href="<?php echo '/card/cancel/cid/' . $card->cardId?>"><i class="cancel-card icon-cancel-circled"></i></a>
										</td>
									</tr>
									<?php } ?>
								</tbody>
							</table>
							<?php } else {
							
							    echo "You haven't registered any cards. Click on the add card button to add a card";
							}?>
						</div>
						<!--
						<div class="recent-orders widget">
							<h2 class="legend">Recent Orders <span class="separator">|</span> <a href="http://asdav2.magento.jml-staging.com/sales/order/history/">View All</a></h2>
							<table class="data-table" id="my-orders-table">
								<colgroup>
									<col width="1">
									<col width="1">
									<col>
									<col width="1">
									<col width="1">
									<col width="135">
								</colgroup>
								<thead>
									<tr class="first last">
										<th>Order #</th>
										<th>Date</th>
										<th>Ship To</th>
										<th><span class="nobr">Order Total</span></th>
										<th>Status</th>
										<th>&nbsp;</th>
									</tr>
								</thead>
								<tbody>
									<tr class="first odd">
										<td>5900000002</td>
										<td><span class="nobr">25/04/2013</span></td>
										<td>Dan Meek</td>
										<td><span class="price">&pound;22.75</span></td>
										<td><em>Pending</em></td>
										<td class="a-center last">
										<a href="http://asdav2.magento.jml-staging.com/sales/order/view/order_id/35861/" class="nobr">Order info</a>
										<span class="separator">|</span> <a href="http://asdav2.magento.jml-staging.com/sales/order/reorder/order_id/35861/" class="nobr">Buy again</a>
										</td>
									</tr>
									<tr class="last even">
										<td>5900000001</td>
										<td><span class="nobr">24/04/2013</span></td>
										<td>Dan Meek</td>
										<td><span class="price">&pound;12.75</span></td>
										<td><em>Pending</em></td>
										<td class="a-center last">
											<a href="http://asdav2.magento.jml-staging.com/sales/order/view/order_id/35860/" class="nobr">Order info</a>
											<span class="separator">|</span> <a href="http://asdav2.magento.jml-staging.com/sales/order/reorder/order_id/35860/" class="nobr">Buy again</a>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
						-->
						<div class="column-50-50 clearfix">
							<div class="col1">
							<div class="widget clearfix">
								<h2 class="legend">Account Information</h2>
								<div class="pageWrapper ">
									<h3 class="box-title">Contact Information <!-- <span class="separator">|</span> <a href="http://asdav2.magento.jml-staging.com/customer/account/edit/">Edit</a> --> </h3>
									<p class="box-content">
										<?php echo $this->userDetails->first_name .' '. $this->userDetails->last_name?><br>
										<?php echo $this->userDetails->user_email?><br>
										<!-- <a href="http://asdav2.magento.jml-staging.com/customer/account/edit/changepass/1/">Change Password</a> -->
									</p>
								</div>
							</div>
							</div>
						</div>
						<div class="column-50-50 clearfix">
						<div class="widget clearfix">
							<h2 class="legend">Address Book</h2>
							<div class="pageWrapper ">
							<div class="col1">
								<div class="info-box">
									<h3 class="box-title">Default Billing Address <span class="separator">|</span> <a href="/address/index/t/2">Edit Address</a></h3>
									<address class="box-content">
										<?php if (is_object($this->billingAddress)) { ?>
										<?php echo $this->userDetails->first_name .' '. $this->userDetails->last_name?><br>
										<?php echo $this->billingAddress->address1?><br>
										<?php echo $this->billingAddress->address2?><br>
										<?php echo $this->billingAddress->city?><br>
										<?php echo $this->billingAddress->county?><br>
										<?php echo $this->billingAddress->post_code?><br>
										<?php }  else { ?>
										    You don't have billing address
										 <?php } ?>
									</address>
								</div>
							</div>
							<div class="col2">
								<div class="info-box">
									<h3 class="box-title">Default Shipping Address <span class="separator">|</span> <a href="/address/index/t/3">Edit Address</a></h3>
                                    <address class="box-content">
										<?php if (is_object($this->shippingAddress)) { ?>
										<?php echo $this->userDetails->first_name .' '. $this->userDetails->last_name?><br>
										<?php echo $this->shippingAddress->address1?><br>
										<?php echo $this->shippingAddress->address2?><br>
										<?php echo $this->shippingAddress->city?><br>
										<?php echo $this->shippingAddress->county?><br>
										<?php echo $this->shippingAddress->post_code?><br>
										<?php }  else { ?>
										    You don't have shipping address
										<?php } ?>
										</address>
									</div>
								</div>
							</div>
							</div>
						</div>
						</div>
					</div>
				</div>		

    		</div>
    	</div>
    </div>
</section>